// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using szablon.Data;

#nullable disable

namespace szablon.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20250622163117_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("szablon.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("EmployeeId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            FirstName = "Ewa",
                            HireDate = new DateTime(2018, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Wiśniewska"
                        },
                        new
                        {
                            EmployeeId = 2,
                            FirstName = "Marek",
                            HireDate = new DateTime(2021, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Lewandowski"
                        },
                        new
                        {
                            EmployeeId = 3,
                            FirstName = "Katarzyna",
                            HireDate = new DateTime(2017, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Zielińska"
                        });
                });

            modelBuilder.Entity("szablon.Models.Nursery", b =>
                {
                    b.Property<int>("NurseryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NurseryId"));

                    b.Property<DateTime>("EstablishmentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("NurseryId");

                    b.ToTable("Nurseries");

                    b.HasData(
                        new
                        {
                            NurseryId = 1,
                            EstablishmentDate = new DateTime(2005, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Zielona Szkółka"
                        },
                        new
                        {
                            NurseryId = 2,
                            EstablishmentDate = new DateTime(2012, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Szkółka Leśna"
                        });
                });

            modelBuilder.Entity("szablon.Models.Responsible", b =>
                {
                    b.Property<int>("BatchId")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("BatchId", "EmployeeId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Responsibles");

                    b.HasData(
                        new
                        {
                            BatchId = 1,
                            EmployeeId = 1,
                            Role = "Supervisor"
                        },
                        new
                        {
                            BatchId = 1,
                            EmployeeId = 3,
                            Role = "Planter"
                        },
                        new
                        {
                            BatchId = 2,
                            EmployeeId = 2,
                            Role = "Assistant"
                        });
                });

            modelBuilder.Entity("szablon.Models.SeedlingBatch", b =>
                {
                    b.Property<int>("BatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BatchId"));

                    b.Property<int>("NurseryId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReadyDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SownDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SpeciesId")
                        .HasColumnType("int");

                    b.HasKey("BatchId");

                    b.HasIndex("NurseryId");

                    b.HasIndex("SpeciesId");

                    b.ToTable("Seedling_Batch");

                    b.HasData(
                        new
                        {
                            BatchId = 1,
                            NurseryId = 1,
                            Quantity = 500,
                            ReadyDate = new DateTime(2029, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SownDate = new DateTime(2024, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SpeciesId = 1
                        },
                        new
                        {
                            BatchId = 2,
                            NurseryId = 2,
                            Quantity = 300,
                            SownDate = new DateTime(2023, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SpeciesId = 3
                        });
                });

            modelBuilder.Entity("szablon.Models.TreeSpecies", b =>
                {
                    b.Property<int>("SpeciesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SpeciesId"));

                    b.Property<int>("GrowthTimeInYears")
                        .HasColumnType("int");

                    b.Property<string>("LatinName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SpeciesId");

                    b.ToTable("Tree_Species");

                    b.HasData(
                        new
                        {
                            SpeciesId = 1,
                            GrowthTimeInYears = 5,
                            LatinName = "Quercus robur"
                        },
                        new
                        {
                            SpeciesId = 2,
                            GrowthTimeInYears = 7,
                            LatinName = "Fagus sylvation"
                        },
                        new
                        {
                            SpeciesId = 3,
                            GrowthTimeInYears = 6,
                            LatinName = "Abies alba"
                        });
                });

            modelBuilder.Entity("szablon.Models.Responsible", b =>
                {
                    b.HasOne("szablon.Models.SeedlingBatch", "SeedlingBatch")
                        .WithMany("Responsibles")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("szablon.Models.Employee", "Employee")
                        .WithMany("Responsibles")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("SeedlingBatch");
                });

            modelBuilder.Entity("szablon.Models.SeedlingBatch", b =>
                {
                    b.HasOne("szablon.Models.Nursery", "Nursery")
                        .WithMany("SeedlingBatches")
                        .HasForeignKey("NurseryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("szablon.Models.TreeSpecies", "TreeSpecies")
                        .WithMany("SeedlingBatches")
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nursery");

                    b.Navigation("TreeSpecies");
                });

            modelBuilder.Entity("szablon.Models.Employee", b =>
                {
                    b.Navigation("Responsibles");
                });

            modelBuilder.Entity("szablon.Models.Nursery", b =>
                {
                    b.Navigation("SeedlingBatches");
                });

            modelBuilder.Entity("szablon.Models.SeedlingBatch", b =>
                {
                    b.Navigation("Responsibles");
                });

            modelBuilder.Entity("szablon.Models.TreeSpecies", b =>
                {
                    b.Navigation("SeedlingBatches");
                });
#pragma warning restore 612, 618
        }
    }
}
